config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
 
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
   
    unauthenticated do
      root "splash#index"
    end
  
   authenticated :user do
      root 'categories#index', as: :authenticated_root
    end

    resources :categories do
      resources :expenses
    end  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    can :manage, :all, user_id: user.id
    can :manage, ::Category, user_id: user.id
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :expenses

  validates :name, presence: true, length: { maximum: 250 }
  validates :icon, presence: true
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :category

  validates :name, presence: true, length: { maximum: 250 }
  validates :amount, presence: true,
                     numericality: { only_decimal: true, greater_than_or_equal_to: 0,
                                     less_than_or_equal_to: 10_000, message: 'must be less than or equal to 10,000' }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :confirmable, :rememberable, :validatable

  has_many :categories
  has_many :expenses, through: :categories
  validates :name, :email, :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation])
    devise_parameter_sanitizer.permit(:account_update,
                                      keys: %i[name email password password_confirmation current_password])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[show edit update destroy]

  def index
    @categories = current_user.categories.includes(:expenses).order(created_at: :desc)
  end

  def show
    @category = Category.find(params[:id])
    @expenses = @category.expenses.order(created_at: :desc)
  end

  def new
    @category = Category.new
  end

  def edit; end

  def create
    @category = current_user.categories.new(category_params)

    if @category.save
      redirect_to @category, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to root_path, flash: { success: 'Category was successfully destroyed.' }
  end

  private

  def set_category
    @category = current_user.categories.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = 'Category not found'
    redirect_to categories_path
  end

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_expense, only: %i[show edit update destroy]
  before_action :set_category

  def index
    @expenses = @category.expenses.order(created_at: :desc)
    @total_amount = @category.expenses.sum(:amount)
  end

  def show; end

  def new
    @category = Category.find(params[:category_id])
    @expense = @category.expenses.new
  end

  def edit
    @categories = current_user.categories
  end

  def create
    @expense = current_user.expenses.new(expense_params)

    if @expense.save
      redirect_to category_expenses_path(@expense.category), notice: 'Expense was successfully created.'
    else
      puts @expense.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @expense.update(expense_params)
      redirect_to @expense, notice: 'Expense was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @expense.destroy
    redirect_to expenses_url, notice: 'Expense was successfully destroyed.'
  end

  private

  def set_category
    @category = Category.find(params[:category_id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = 'Category not found'
    redirect_to categories_path
  end

  def set_expense
    @expense = current_user.expenses.find(params[:id])
  end

  def expense_params
    params.require(:expense).permit(:category_id, :name, :amount)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>" class="flex justify-between items-center m-3 p-3 bg-white text-terciary">
  <%=image_tag category.icon, class: "w-16 h-16" %>
  <h5 class="grow text-left px-3"><%= category.name %></h5>
  <h5>$<%= category.expenses.map {|expense| expense.amount}.sum %></h5>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container mx-auto bg-white px-3 py-2">
    <div class="relative z-0 w-full my-2 group">
      <%= form.text_field :name, autocomplete: "name", autofocus: true, class: "block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer", placeholder: "Name", required: true %>
    </div>

    <div class="relative z-0 w-full my-2 group">
      <%= form.url_field :icon, autocomplete: "icon", autofocus: true, class: "block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer", placeholder: "Icon URL", required: true %>
    </div>

    <div class="text-gray-200 font-light text-center my-2 w-full">
      <%= form.submit "Submit", class: "bg-primary hover:bg-blue-700 block py-3 px-4 rounded" %>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= render 'form', category: @category %>

<%= link_to "Cancel", category_path(@category) %>

app/views/categories/index.html.erb
<div class="flex flex-col justify-between min-h-screen">
  <section class="container mx-auto flex justify-start items-center bg-primary text-white font-light px-3 py-4">
   <i class="fa-solid fa-bars fa-xl" id="hamburger-btn"></i>
    <h5 class="font-light grow text-center">CATEGORIES</h5>
    <a href="#" class="ml-auto">
      <i class="fa-solid fa-search fa-lg"></i>
    </a>
  </section>
  <div id="menu-list" class="hidden  bg-gray-200 p-4">
    <%= link_to "Home", root_path, class: "block py-2 text-gray-800 hover:text-gray-600 mb-4" %>
     <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "block py-2 text-gray-800 hover:text-gray-600 mb-4" %>
  </div>
   
  <p class="text-green-500 px-3"><%= notice %></p>
  
  <div id="categories" class="grow">
    <% @categories.each do |category| %>
      <%= link_to category  do %>
        <%= render category %>
      <% end %>
    <% end %>
  </div>
  <div class="bg-secondary p-4 text-center text-3xl text-white font-light">
    <% if params[:action] == 'new' %>
      <%= link_to "Back", categories_path, class: "border border-white hover:opacity-70 block p-4 rounded" %>
    <% else %>
      <%= link_to "New Category", new_category_path, class: "border border-white hover:opacity-70 block p-4 rounded" %>
    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="container mx-auto flex justify-start items-center bg-primary text-white font-light px-3 py-4">
<%= link_to categories_path, class: "flex items-center mt-4 text-gray-600 hover:text-gray-900" do %>
<span>&lt;</span>
<% end %>
<h2 class="font-light grow text-center">New Category</h2> 
</div>
<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<div class="flex flex-col justify-between min-h-screen">
  <div class="container mx-auto flex justify-start items-center bg-primary text-white font-light px-3 py-4">
    <%= link_to categories_path do %>
      <i class="fa-solid fa-arrow-left fa-xl "></i>
    <% end %>
    <h5 class="font-light grow text-center">EXPENSES</h5> 
  </div>

  <p class="text-green-500 p-3"><%= notice %></p>
<h5 class="m-3 p-3 bg-white text-terciary text-center text-2xl">Total for <%= @category.name %>  $<%= @category.expenses.sum(:amount) %></h5> 
  <div class="expenses-container overflow-y-auto">
    <% @expenses.each do |expense| %> 
      <div class="flex justify-between items-center m-3 p-3 bg-white text-terciary">
        <div>
          <h5><%= expense.name %></h5> 
          <h5><%= expense.created_at.strftime("%Y-%m-%d") %></h5> 
        </div>
        <h5>$<%= expense.amount %></h5> 
      </div>
    <% end %>
    
  </div>

  <div class="bg-secondary p-4 text-center text-3xl text-white font-light">
    <%= link_to "New Expense", new_category_expense_path(@category), class: "border border-white hover:bg-blue-700 block p-4 rounded" %>
  </div> 
</div>

app/views/expenses/_expense.html.erb
<div id="<%= dom_id expense %>">
  <p>
    <strong>Amount:</strong>
    <%= number_to_currency(expense.amount) %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= expense.category_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= expense.name %>
  </p>

  
</div>

app/views/expenses/_form.html.erb
<%= form_with(model: [@category, @expense]) do |form| %>
  <% if @expense.errors.any? %>
    <div id="error_explanation" class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
      <h2 class="font-bold"> <%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul class="mt-3 list-disc list-inside">
        <% @expense.errors.full_messages.each do |message| %>
          <li> <%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-4">
    <%= form.label :name, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :name, required: true, class: "form-input mt-1 block w-full" %>
  </div>

  <div class="mb-4">
    <%= form.label :amount, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.number_field :amount, required: true, class: "form-input mt-1 block w-full" %>
  </div>

 <div class="mb-4">
  <%= form.label :category_id, "Category", class: "block text-gray-700 text-sm font-bold mb-2" %>
  <%= form.collection_select :category_id, Category.all, :id, :name, { include_blank: "Select Category" }, { class: "form-select mt-1 block w-full" } %>
</div>

  <div class="mb-4">
    <%= form.submit "Save", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render "form", expense: @expenses %>

<br>

<div>
  <%= link_to "Show this expense", @expense %> |
  <%= link_to "Back to expenses", expense_path %>
</div>

app/views/expenses/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container mx-auto flex justify-start items-center bg-primary text-white font-light px-3 py-4 exp-text">
  <%= link_to categories_path do %>
    <i class="fa-solid fa-arrow-left fa-xl"></i>
  <% end %>
  <h5 class="font-light grow text-center">Expenses for <%= @category.name %></h5>
</div>

<div id="payments">
  <% @category.expenses.each do |expense| %>
    <%= render expense %>
  <% end %>
</div>

<div class="total-amount">
  <p>Total Amount: <%= number_to_currency(@category.expenses.sum(:amount)) %></p>
</div>

app/views/expenses/new.html.erb
<div class="flex flex-col">
  <div class="container mx-auto flex justify-start items-center bg-primary text-white font-light px-3 py-4">
    <%= link_to categories_path do %>
      <i class="fa-solid fa-arrow-left fa-xl"></i>
    <% end %>
    <h5 class="font-light grow text-center">ADD EXPENSE</h5>
  </div>

  <%= render 'form', expense: @expense %>
</div>

app/views/expenses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @expense %>
<%= @expense.category.id %>

<div>
  <%= link_to "Edit this expense", edit_expense_path(@expense) %> |
  <%= link_to "Back to expenses", expenses_path %>

  <%= button_to "Destroy this expense", @expense, method: :delete %>
</div>

app/views/layouts/_navbar.html.erb
<div class="fixed w-full left-0 top-0 bg-transparent z-10 h-screen hidden transition-all" id="backdrop"></div>
<nav id="mobile-menu" class="fixed w-3/4 left-0 top-0 bg-blue-400 opacity-90 text-white z-20 h-screen p-4 flex justify-center items-center gap-10 -translate-x-full transition-all">
  <% if user_signed_in? %>
    <h3 class="absolute top-10 text-sm">Signed in as <%= current_user.name %></h3>
  <% end %>
  <ul>
    <% if user_signed_in? %>
    <li><%= button_to "sign out", destroy_user_session_path, method: :delete, class: "text-2xl uppercase"%></li>
    <% else %>
    <li><%= link_to "sign in", new_user_session_path, class: "text-2xl uppercase"%></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExpenseTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag 'application', 'application' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">


    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'custom' %>

  </head>

 <body>
  
 <main class=" bg-gray-100 container mx-auto max-w-sm">
      <%= render partial: "layouts/navbar" %>
      <%= yield %>
      <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    </main>
    
  </body>
</html>

app/views/splash/index.html.erb
<section class="container mx-auto flex justify-center">
  <div class="w-screen min-h-screen mx-3 py-3 text-center flex flex-col">
    <div class="grow text-center flex justify-center items-center">
      <div class="italic font-black text-3xl text-terciary">My Expense Tracker</div>
    </div>
    <div class="text">
      <div class="text-gray-300  my-2"><%= link_to "LOG IN", new_user_session_path, class: "bg-primary hover:bg-blue-700 text-white block py-3 px-4 rounded-sm" %></div>
      <div class="text-gray-300  my-2"><%= link_to "SIGN UP", new_user_registration_path, class: "bg-primary hover:bg-blue-700 text-white block py-3 px-4 rounded-sm" %></div>
    </div>
  </div>
</section>